Parameters:
  DefaultVPC:
    Type: 'List<AWS::EC2::VPC::Id>'

  DefaultSubnets:
    Type: 'List<AWS::EC2::Subnet::Id>'

  DefaultSecurityGroup:
    Type: 'List<AWS::EC2::SecurityGroup::Id>'

Resources:
  ECSTaskExecutionRole:
    Type: AWS::IAM::Role
    DependsOn: ECSTaskExecutionPolicy
    Properties: 
      AssumeRolePolicyDocument:
        Statement: 
         - 
          Effect: Allow
          Principal:
            Service:
              - ecs-tasks.amazonaws.com
          Action: sts:AssumeRole
      Policies:
        -
          Ref: ECSTaskExecutionPolicy

  ECSTaskExecutionPolicy:
    Type: AWS::IAM::Policy
    Properties:
      PolicyName: ECSTaskExecutionPolicy
      PolicyDocument:
        Statement:
        -
          Effect: Allow
          Action:
            - "ecr:GetAuthorizationToken"
              "ecr:BatchCheckLayerAvailability"
              "ecr:GetDownloadUrlForLayer"
              "ecr:BatchGetImage"
              "logs:CreateLogStream"
              "logs:PutLogEvents"
          Resource: "*"
      
  WBIDVDefaultECSTask:
    Type: AWS::ECS::TaskDefinition
    DependsOn: ECSTaskExecutionPolicy
    Properties: 
      ContainerDefinitions: 
        - Cpu: 256
          Essential: true
          HealthCheck: 
            Command: 
              - CMD-SHELL
                curl -f http://localhost || exit 1
            Interval: 30
            Retries: 5
            StartPeriod: 30
            Timeout: 60
          Image: wb-app/docker-images:latest
          LogConfiguration: 
            LogDriver: awslogs
          MemoryReservation: 200
          Name: wb-fargate-container
          PortMappings: 
           - ContainerPort: 80
      Cpu: '1024'
      ExecutionRoleArn: !GetAtt ECSTaskExecutionRole.Arn
      Memory: '2048'
      NetworkMode: awsvpc
